name: release-on-tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install NPM
        run: npm install
      - name: Build
        run: npm run build
      - name: pwd
        run: pwd
      - name: ls
        run: ls -la
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.js
          asset_name: main.js
          tag: ${{ github.ref }}
          overwrite: true
